package com.hans.boot_mybatis_generator_demo.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andIconIsNull() {
            addCriterion("icon is null");
            return (Criteria) this;
        }

        public Criteria andIconIsNotNull() {
            addCriterion("icon is not null");
            return (Criteria) this;
        }

        public Criteria andIconEqualTo(String value) {
            addCriterion("icon =", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotEqualTo(String value) {
            addCriterion("icon <>", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThan(String value) {
            addCriterion("icon >", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThanOrEqualTo(String value) {
            addCriterion("icon >=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThan(String value) {
            addCriterion("icon <", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThanOrEqualTo(String value) {
            addCriterion("icon <=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLike(String value) {
            addCriterion("icon like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotLike(String value) {
            addCriterion("icon not like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconIn(List<String> values) {
            addCriterion("icon in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotIn(List<String> values) {
            addCriterion("icon not in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconBetween(String value1, String value2) {
            addCriterion("icon between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotBetween(String value1, String value2) {
            addCriterion("icon not between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andTictetzIsNull() {
            addCriterion("tictetz is null");
            return (Criteria) this;
        }

        public Criteria andTictetzIsNotNull() {
            addCriterion("tictetz is not null");
            return (Criteria) this;
        }

        public Criteria andTictetzEqualTo(Long value) {
            addCriterion("tictetz =", value, "tictetz");
            return (Criteria) this;
        }

        public Criteria andTictetzNotEqualTo(Long value) {
            addCriterion("tictetz <>", value, "tictetz");
            return (Criteria) this;
        }

        public Criteria andTictetzGreaterThan(Long value) {
            addCriterion("tictetz >", value, "tictetz");
            return (Criteria) this;
        }

        public Criteria andTictetzGreaterThanOrEqualTo(Long value) {
            addCriterion("tictetz >=", value, "tictetz");
            return (Criteria) this;
        }

        public Criteria andTictetzLessThan(Long value) {
            addCriterion("tictetz <", value, "tictetz");
            return (Criteria) this;
        }

        public Criteria andTictetzLessThanOrEqualTo(Long value) {
            addCriterion("tictetz <=", value, "tictetz");
            return (Criteria) this;
        }

        public Criteria andTictetzIn(List<Long> values) {
            addCriterion("tictetz in", values, "tictetz");
            return (Criteria) this;
        }

        public Criteria andTictetzNotIn(List<Long> values) {
            addCriterion("tictetz not in", values, "tictetz");
            return (Criteria) this;
        }

        public Criteria andTictetzBetween(Long value1, Long value2) {
            addCriterion("tictetz between", value1, value2, "tictetz");
            return (Criteria) this;
        }

        public Criteria andTictetzNotBetween(Long value1, Long value2) {
            addCriterion("tictetz not between", value1, value2, "tictetz");
            return (Criteria) this;
        }

        public Criteria andCashIsNull() {
            addCriterion("cash is null");
            return (Criteria) this;
        }

        public Criteria andCashIsNotNull() {
            addCriterion("cash is not null");
            return (Criteria) this;
        }

        public Criteria andCashEqualTo(BigDecimal value) {
            addCriterion("cash =", value, "cash");
            return (Criteria) this;
        }

        public Criteria andCashNotEqualTo(BigDecimal value) {
            addCriterion("cash <>", value, "cash");
            return (Criteria) this;
        }

        public Criteria andCashGreaterThan(BigDecimal value) {
            addCriterion("cash >", value, "cash");
            return (Criteria) this;
        }

        public Criteria andCashGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cash >=", value, "cash");
            return (Criteria) this;
        }

        public Criteria andCashLessThan(BigDecimal value) {
            addCriterion("cash <", value, "cash");
            return (Criteria) this;
        }

        public Criteria andCashLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cash <=", value, "cash");
            return (Criteria) this;
        }

        public Criteria andCashIn(List<BigDecimal> values) {
            addCriterion("cash in", values, "cash");
            return (Criteria) this;
        }

        public Criteria andCashNotIn(List<BigDecimal> values) {
            addCriterion("cash not in", values, "cash");
            return (Criteria) this;
        }

        public Criteria andCashBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cash between", value1, value2, "cash");
            return (Criteria) this;
        }

        public Criteria andCashNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cash not between", value1, value2, "cash");
            return (Criteria) this;
        }

        public Criteria andBountyIsNull() {
            addCriterion("bounty is null");
            return (Criteria) this;
        }

        public Criteria andBountyIsNotNull() {
            addCriterion("bounty is not null");
            return (Criteria) this;
        }

        public Criteria andBountyEqualTo(BigDecimal value) {
            addCriterion("bounty =", value, "bounty");
            return (Criteria) this;
        }

        public Criteria andBountyNotEqualTo(BigDecimal value) {
            addCriterion("bounty <>", value, "bounty");
            return (Criteria) this;
        }

        public Criteria andBountyGreaterThan(BigDecimal value) {
            addCriterion("bounty >", value, "bounty");
            return (Criteria) this;
        }

        public Criteria andBountyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bounty >=", value, "bounty");
            return (Criteria) this;
        }

        public Criteria andBountyLessThan(BigDecimal value) {
            addCriterion("bounty <", value, "bounty");
            return (Criteria) this;
        }

        public Criteria andBountyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bounty <=", value, "bounty");
            return (Criteria) this;
        }

        public Criteria andBountyIn(List<BigDecimal> values) {
            addCriterion("bounty in", values, "bounty");
            return (Criteria) this;
        }

        public Criteria andBountyNotIn(List<BigDecimal> values) {
            addCriterion("bounty not in", values, "bounty");
            return (Criteria) this;
        }

        public Criteria andBountyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bounty between", value1, value2, "bounty");
            return (Criteria) this;
        }

        public Criteria andBountyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bounty not between", value1, value2, "bounty");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andRobotIsNull() {
            addCriterion("robot is null");
            return (Criteria) this;
        }

        public Criteria andRobotIsNotNull() {
            addCriterion("robot is not null");
            return (Criteria) this;
        }

        public Criteria andRobotEqualTo(Integer value) {
            addCriterion("robot =", value, "robot");
            return (Criteria) this;
        }

        public Criteria andRobotNotEqualTo(Integer value) {
            addCriterion("robot <>", value, "robot");
            return (Criteria) this;
        }

        public Criteria andRobotGreaterThan(Integer value) {
            addCriterion("robot >", value, "robot");
            return (Criteria) this;
        }

        public Criteria andRobotGreaterThanOrEqualTo(Integer value) {
            addCriterion("robot >=", value, "robot");
            return (Criteria) this;
        }

        public Criteria andRobotLessThan(Integer value) {
            addCriterion("robot <", value, "robot");
            return (Criteria) this;
        }

        public Criteria andRobotLessThanOrEqualTo(Integer value) {
            addCriterion("robot <=", value, "robot");
            return (Criteria) this;
        }

        public Criteria andRobotIn(List<Integer> values) {
            addCriterion("robot in", values, "robot");
            return (Criteria) this;
        }

        public Criteria andRobotNotIn(List<Integer> values) {
            addCriterion("robot not in", values, "robot");
            return (Criteria) this;
        }

        public Criteria andRobotBetween(Integer value1, Integer value2) {
            addCriterion("robot between", value1, value2, "robot");
            return (Criteria) this;
        }

        public Criteria andRobotNotBetween(Integer value1, Integer value2) {
            addCriterion("robot not between", value1, value2, "robot");
            return (Criteria) this;
        }

        public Criteria andQkCoinIsNull() {
            addCriterion("qk_coin is null");
            return (Criteria) this;
        }

        public Criteria andQkCoinIsNotNull() {
            addCriterion("qk_coin is not null");
            return (Criteria) this;
        }

        public Criteria andQkCoinEqualTo(Long value) {
            addCriterion("qk_coin =", value, "qkCoin");
            return (Criteria) this;
        }

        public Criteria andQkCoinNotEqualTo(Long value) {
            addCriterion("qk_coin <>", value, "qkCoin");
            return (Criteria) this;
        }

        public Criteria andQkCoinGreaterThan(Long value) {
            addCriterion("qk_coin >", value, "qkCoin");
            return (Criteria) this;
        }

        public Criteria andQkCoinGreaterThanOrEqualTo(Long value) {
            addCriterion("qk_coin >=", value, "qkCoin");
            return (Criteria) this;
        }

        public Criteria andQkCoinLessThan(Long value) {
            addCriterion("qk_coin <", value, "qkCoin");
            return (Criteria) this;
        }

        public Criteria andQkCoinLessThanOrEqualTo(Long value) {
            addCriterion("qk_coin <=", value, "qkCoin");
            return (Criteria) this;
        }

        public Criteria andQkCoinIn(List<Long> values) {
            addCriterion("qk_coin in", values, "qkCoin");
            return (Criteria) this;
        }

        public Criteria andQkCoinNotIn(List<Long> values) {
            addCriterion("qk_coin not in", values, "qkCoin");
            return (Criteria) this;
        }

        public Criteria andQkCoinBetween(Long value1, Long value2) {
            addCriterion("qk_coin between", value1, value2, "qkCoin");
            return (Criteria) this;
        }

        public Criteria andQkCoinNotBetween(Long value1, Long value2) {
            addCriterion("qk_coin not between", value1, value2, "qkCoin");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andEmailAuthenticationIsNull() {
            addCriterion("email_authentication is null");
            return (Criteria) this;
        }

        public Criteria andEmailAuthenticationIsNotNull() {
            addCriterion("email_authentication is not null");
            return (Criteria) this;
        }

        public Criteria andEmailAuthenticationEqualTo(Integer value) {
            addCriterion("email_authentication =", value, "emailAuthentication");
            return (Criteria) this;
        }

        public Criteria andEmailAuthenticationNotEqualTo(Integer value) {
            addCriterion("email_authentication <>", value, "emailAuthentication");
            return (Criteria) this;
        }

        public Criteria andEmailAuthenticationGreaterThan(Integer value) {
            addCriterion("email_authentication >", value, "emailAuthentication");
            return (Criteria) this;
        }

        public Criteria andEmailAuthenticationGreaterThanOrEqualTo(Integer value) {
            addCriterion("email_authentication >=", value, "emailAuthentication");
            return (Criteria) this;
        }

        public Criteria andEmailAuthenticationLessThan(Integer value) {
            addCriterion("email_authentication <", value, "emailAuthentication");
            return (Criteria) this;
        }

        public Criteria andEmailAuthenticationLessThanOrEqualTo(Integer value) {
            addCriterion("email_authentication <=", value, "emailAuthentication");
            return (Criteria) this;
        }

        public Criteria andEmailAuthenticationIn(List<Integer> values) {
            addCriterion("email_authentication in", values, "emailAuthentication");
            return (Criteria) this;
        }

        public Criteria andEmailAuthenticationNotIn(List<Integer> values) {
            addCriterion("email_authentication not in", values, "emailAuthentication");
            return (Criteria) this;
        }

        public Criteria andEmailAuthenticationBetween(Integer value1, Integer value2) {
            addCriterion("email_authentication between", value1, value2, "emailAuthentication");
            return (Criteria) this;
        }

        public Criteria andEmailAuthenticationNotBetween(Integer value1, Integer value2) {
            addCriterion("email_authentication not between", value1, value2, "emailAuthentication");
            return (Criteria) this;
        }

        public Criteria andFirstNameIsNull() {
            addCriterion("first_name is null");
            return (Criteria) this;
        }

        public Criteria andFirstNameIsNotNull() {
            addCriterion("first_name is not null");
            return (Criteria) this;
        }

        public Criteria andFirstNameEqualTo(String value) {
            addCriterion("first_name =", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameNotEqualTo(String value) {
            addCriterion("first_name <>", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameGreaterThan(String value) {
            addCriterion("first_name >", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameGreaterThanOrEqualTo(String value) {
            addCriterion("first_name >=", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameLessThan(String value) {
            addCriterion("first_name <", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameLessThanOrEqualTo(String value) {
            addCriterion("first_name <=", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameLike(String value) {
            addCriterion("first_name like", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameNotLike(String value) {
            addCriterion("first_name not like", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameIn(List<String> values) {
            addCriterion("first_name in", values, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameNotIn(List<String> values) {
            addCriterion("first_name not in", values, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameBetween(String value1, String value2) {
            addCriterion("first_name between", value1, value2, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameNotBetween(String value1, String value2) {
            addCriterion("first_name not between", value1, value2, "firstName");
            return (Criteria) this;
        }

        public Criteria andLastNameIsNull() {
            addCriterion("last_name is null");
            return (Criteria) this;
        }

        public Criteria andLastNameIsNotNull() {
            addCriterion("last_name is not null");
            return (Criteria) this;
        }

        public Criteria andLastNameEqualTo(String value) {
            addCriterion("last_name =", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotEqualTo(String value) {
            addCriterion("last_name <>", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameGreaterThan(String value) {
            addCriterion("last_name >", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameGreaterThanOrEqualTo(String value) {
            addCriterion("last_name >=", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameLessThan(String value) {
            addCriterion("last_name <", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameLessThanOrEqualTo(String value) {
            addCriterion("last_name <=", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameLike(String value) {
            addCriterion("last_name like", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotLike(String value) {
            addCriterion("last_name not like", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameIn(List<String> values) {
            addCriterion("last_name in", values, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotIn(List<String> values) {
            addCriterion("last_name not in", values, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameBetween(String value1, String value2) {
            addCriterion("last_name between", value1, value2, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotBetween(String value1, String value2) {
            addCriterion("last_name not between", value1, value2, "lastName");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andChampionTipIsNull() {
            addCriterion("champion_tip is null");
            return (Criteria) this;
        }

        public Criteria andChampionTipIsNotNull() {
            addCriterion("champion_tip is not null");
            return (Criteria) this;
        }

        public Criteria andChampionTipEqualTo(Integer value) {
            addCriterion("champion_tip =", value, "championTip");
            return (Criteria) this;
        }

        public Criteria andChampionTipNotEqualTo(Integer value) {
            addCriterion("champion_tip <>", value, "championTip");
            return (Criteria) this;
        }

        public Criteria andChampionTipGreaterThan(Integer value) {
            addCriterion("champion_tip >", value, "championTip");
            return (Criteria) this;
        }

        public Criteria andChampionTipGreaterThanOrEqualTo(Integer value) {
            addCriterion("champion_tip >=", value, "championTip");
            return (Criteria) this;
        }

        public Criteria andChampionTipLessThan(Integer value) {
            addCriterion("champion_tip <", value, "championTip");
            return (Criteria) this;
        }

        public Criteria andChampionTipLessThanOrEqualTo(Integer value) {
            addCriterion("champion_tip <=", value, "championTip");
            return (Criteria) this;
        }

        public Criteria andChampionTipIn(List<Integer> values) {
            addCriterion("champion_tip in", values, "championTip");
            return (Criteria) this;
        }

        public Criteria andChampionTipNotIn(List<Integer> values) {
            addCriterion("champion_tip not in", values, "championTip");
            return (Criteria) this;
        }

        public Criteria andChampionTipBetween(Integer value1, Integer value2) {
            addCriterion("champion_tip between", value1, value2, "championTip");
            return (Criteria) this;
        }

        public Criteria andChampionTipNotBetween(Integer value1, Integer value2) {
            addCriterion("champion_tip not between", value1, value2, "championTip");
            return (Criteria) this;
        }

        public Criteria andMyInvitationCodeIsNull() {
            addCriterion("my_invitation_code is null");
            return (Criteria) this;
        }

        public Criteria andMyInvitationCodeIsNotNull() {
            addCriterion("my_invitation_code is not null");
            return (Criteria) this;
        }

        public Criteria andMyInvitationCodeEqualTo(String value) {
            addCriterion("my_invitation_code =", value, "myInvitationCode");
            return (Criteria) this;
        }

        public Criteria andMyInvitationCodeNotEqualTo(String value) {
            addCriterion("my_invitation_code <>", value, "myInvitationCode");
            return (Criteria) this;
        }

        public Criteria andMyInvitationCodeGreaterThan(String value) {
            addCriterion("my_invitation_code >", value, "myInvitationCode");
            return (Criteria) this;
        }

        public Criteria andMyInvitationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("my_invitation_code >=", value, "myInvitationCode");
            return (Criteria) this;
        }

        public Criteria andMyInvitationCodeLessThan(String value) {
            addCriterion("my_invitation_code <", value, "myInvitationCode");
            return (Criteria) this;
        }

        public Criteria andMyInvitationCodeLessThanOrEqualTo(String value) {
            addCriterion("my_invitation_code <=", value, "myInvitationCode");
            return (Criteria) this;
        }

        public Criteria andMyInvitationCodeLike(String value) {
            addCriterion("my_invitation_code like", value, "myInvitationCode");
            return (Criteria) this;
        }

        public Criteria andMyInvitationCodeNotLike(String value) {
            addCriterion("my_invitation_code not like", value, "myInvitationCode");
            return (Criteria) this;
        }

        public Criteria andMyInvitationCodeIn(List<String> values) {
            addCriterion("my_invitation_code in", values, "myInvitationCode");
            return (Criteria) this;
        }

        public Criteria andMyInvitationCodeNotIn(List<String> values) {
            addCriterion("my_invitation_code not in", values, "myInvitationCode");
            return (Criteria) this;
        }

        public Criteria andMyInvitationCodeBetween(String value1, String value2) {
            addCriterion("my_invitation_code between", value1, value2, "myInvitationCode");
            return (Criteria) this;
        }

        public Criteria andMyInvitationCodeNotBetween(String value1, String value2) {
            addCriterion("my_invitation_code not between", value1, value2, "myInvitationCode");
            return (Criteria) this;
        }

        public Criteria andOtherInvitationCodeIsNull() {
            addCriterion("other_invitation_code is null");
            return (Criteria) this;
        }

        public Criteria andOtherInvitationCodeIsNotNull() {
            addCriterion("other_invitation_code is not null");
            return (Criteria) this;
        }

        public Criteria andOtherInvitationCodeEqualTo(String value) {
            addCriterion("other_invitation_code =", value, "otherInvitationCode");
            return (Criteria) this;
        }

        public Criteria andOtherInvitationCodeNotEqualTo(String value) {
            addCriterion("other_invitation_code <>", value, "otherInvitationCode");
            return (Criteria) this;
        }

        public Criteria andOtherInvitationCodeGreaterThan(String value) {
            addCriterion("other_invitation_code >", value, "otherInvitationCode");
            return (Criteria) this;
        }

        public Criteria andOtherInvitationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("other_invitation_code >=", value, "otherInvitationCode");
            return (Criteria) this;
        }

        public Criteria andOtherInvitationCodeLessThan(String value) {
            addCriterion("other_invitation_code <", value, "otherInvitationCode");
            return (Criteria) this;
        }

        public Criteria andOtherInvitationCodeLessThanOrEqualTo(String value) {
            addCriterion("other_invitation_code <=", value, "otherInvitationCode");
            return (Criteria) this;
        }

        public Criteria andOtherInvitationCodeLike(String value) {
            addCriterion("other_invitation_code like", value, "otherInvitationCode");
            return (Criteria) this;
        }

        public Criteria andOtherInvitationCodeNotLike(String value) {
            addCriterion("other_invitation_code not like", value, "otherInvitationCode");
            return (Criteria) this;
        }

        public Criteria andOtherInvitationCodeIn(List<String> values) {
            addCriterion("other_invitation_code in", values, "otherInvitationCode");
            return (Criteria) this;
        }

        public Criteria andOtherInvitationCodeNotIn(List<String> values) {
            addCriterion("other_invitation_code not in", values, "otherInvitationCode");
            return (Criteria) this;
        }

        public Criteria andOtherInvitationCodeBetween(String value1, String value2) {
            addCriterion("other_invitation_code between", value1, value2, "otherInvitationCode");
            return (Criteria) this;
        }

        public Criteria andOtherInvitationCodeNotBetween(String value1, String value2) {
            addCriterion("other_invitation_code not between", value1, value2, "otherInvitationCode");
            return (Criteria) this;
        }

        public Criteria andGameCompletionTimesIsNull() {
            addCriterion("game_completion_times is null");
            return (Criteria) this;
        }

        public Criteria andGameCompletionTimesIsNotNull() {
            addCriterion("game_completion_times is not null");
            return (Criteria) this;
        }

        public Criteria andGameCompletionTimesEqualTo(Integer value) {
            addCriterion("game_completion_times =", value, "gameCompletionTimes");
            return (Criteria) this;
        }

        public Criteria andGameCompletionTimesNotEqualTo(Integer value) {
            addCriterion("game_completion_times <>", value, "gameCompletionTimes");
            return (Criteria) this;
        }

        public Criteria andGameCompletionTimesGreaterThan(Integer value) {
            addCriterion("game_completion_times >", value, "gameCompletionTimes");
            return (Criteria) this;
        }

        public Criteria andGameCompletionTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("game_completion_times >=", value, "gameCompletionTimes");
            return (Criteria) this;
        }

        public Criteria andGameCompletionTimesLessThan(Integer value) {
            addCriterion("game_completion_times <", value, "gameCompletionTimes");
            return (Criteria) this;
        }

        public Criteria andGameCompletionTimesLessThanOrEqualTo(Integer value) {
            addCriterion("game_completion_times <=", value, "gameCompletionTimes");
            return (Criteria) this;
        }

        public Criteria andGameCompletionTimesIn(List<Integer> values) {
            addCriterion("game_completion_times in", values, "gameCompletionTimes");
            return (Criteria) this;
        }

        public Criteria andGameCompletionTimesNotIn(List<Integer> values) {
            addCriterion("game_completion_times not in", values, "gameCompletionTimes");
            return (Criteria) this;
        }

        public Criteria andGameCompletionTimesBetween(Integer value1, Integer value2) {
            addCriterion("game_completion_times between", value1, value2, "gameCompletionTimes");
            return (Criteria) this;
        }

        public Criteria andGameCompletionTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("game_completion_times not between", value1, value2, "gameCompletionTimes");
            return (Criteria) this;
        }

        public Criteria andSignStatuIsNull() {
            addCriterion("sign_statu is null");
            return (Criteria) this;
        }

        public Criteria andSignStatuIsNotNull() {
            addCriterion("sign_statu is not null");
            return (Criteria) this;
        }

        public Criteria andSignStatuEqualTo(Integer value) {
            addCriterion("sign_statu =", value, "signStatu");
            return (Criteria) this;
        }

        public Criteria andSignStatuNotEqualTo(Integer value) {
            addCriterion("sign_statu <>", value, "signStatu");
            return (Criteria) this;
        }

        public Criteria andSignStatuGreaterThan(Integer value) {
            addCriterion("sign_statu >", value, "signStatu");
            return (Criteria) this;
        }

        public Criteria andSignStatuGreaterThanOrEqualTo(Integer value) {
            addCriterion("sign_statu >=", value, "signStatu");
            return (Criteria) this;
        }

        public Criteria andSignStatuLessThan(Integer value) {
            addCriterion("sign_statu <", value, "signStatu");
            return (Criteria) this;
        }

        public Criteria andSignStatuLessThanOrEqualTo(Integer value) {
            addCriterion("sign_statu <=", value, "signStatu");
            return (Criteria) this;
        }

        public Criteria andSignStatuIn(List<Integer> values) {
            addCriterion("sign_statu in", values, "signStatu");
            return (Criteria) this;
        }

        public Criteria andSignStatuNotIn(List<Integer> values) {
            addCriterion("sign_statu not in", values, "signStatu");
            return (Criteria) this;
        }

        public Criteria andSignStatuBetween(Integer value1, Integer value2) {
            addCriterion("sign_statu between", value1, value2, "signStatu");
            return (Criteria) this;
        }

        public Criteria andSignStatuNotBetween(Integer value1, Integer value2) {
            addCriterion("sign_statu not between", value1, value2, "signStatu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}